SET autocommit=0;
START TRANSACTION; 
INSERT INTO AN002_RUOLO (
	 AN002_DESCRIZIONE,
     AN002_COD_RUOLO,
     AN002_COD_UTENTE_CREAZIONE
)
VALUES (
	'CREATE, UPDATE, DELETE, READ',
    'ADMIN',
    'PA'
);

INSERT INTO AN002_RUOLO (
	 AN002_DESCRIZIONE,
     AN002_COD_RUOLO,
     AN002_COD_UTENTE_CREAZIONE
)
VALUES (
	'CREATE, UPDATE, READ',
    'TRUSTED',
    'PA'
);

INSERT INTO AN002_RUOLO (
	 AN002_DESCRIZIONE,
     AN002_COD_RUOLO,
     AN002_COD_UTENTE_CREAZIONE
)
VALUES (
	'UPDATE, READ',
    'SIMPLE_USER',
    'PA'
);

SELECT * FROM Base.AN002_RUOLO;

ROLLBACK;